#! /bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

sed 's/$/ sentenceends/'             | 
hfst-proc2 $DIR/tokenize.pmatch.hfst |
grep -v "^$"                         |
grep -v "^[|]$"                      |
sed 's/sentenceends//' 
